# Generated by Django 4.0.4 on 2022-05-17 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barrio',
            fields=[
                ('idBarrio', models.AutoField(primary_key=True, serialize=False, verbose_name='id_barrio')),
                ('nombreBarrio', models.CharField(max_length=30, unique=True, verbose_name='nom_barrio')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('idCita', models.AutoField(primary_key=True, serialize=False, verbose_name='id_cita')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.AutoField(primary_key=True, serialize=False, verbose_name='id_cidudad')),
                ('nombreCidudad', models.CharField(max_length=30, verbose_name='nombre_ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idCliente', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_cliente')),
                ('nombres', models.CharField(max_length=30, verbose_name='nombres')),
                ('apellidos', models.CharField(max_length=30, verbose_name='apellidos')),
                ('fechaNacimiento', models.DateField()),
                ('edad', models.IntegerField(default=0)),
                ('telefono', models.IntegerField(default=0)),
                ('email', models.EmailField(max_length=30, verbose_name='correo')),
                ('direccion', models.CharField(max_length=30, verbose_name='direccion')),
                ('estado', models.BooleanField(default=True)),
                ('idBarrio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_barrio', to='tiomikeApp.barrio')),
                ('idCiudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_ciudad', to='tiomikeApp.ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepartamento', models.AutoField(primary_key=True, serialize=False, verbose_name='id_departamento')),
                ('nombreDepartamento', models.CharField(max_length=20, unique=True, verbose_name='nombre_departamento')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleFactura',
            fields=[
                ('idDetalleFactura', models.AutoField(primary_key=True, serialize=False, verbose_name='id_detalle_factura')),
                ('cantidad', models.IntegerField(default=0, verbose_name='cantidad')),
                ('precioVenta', models.FloatField(default=0, verbose_name='precio_venta')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False, verbose_name='id_estado')),
                ('descripcion', models.CharField(max_length=30, unique=True, verbose_name='descripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idGenero', models.AutoField(primary_key=True, serialize=False, verbose_name='id_genero')),
                ('nombreGenero', models.CharField(max_length=100, verbose_name='nombre_genero')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('idRaza', models.AutoField(primary_key=True, serialize=False, verbose_name='id_raza')),
                ('descripcion', models.CharField(max_length=60, unique=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_rol')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Tamano',
            fields=[
                ('idTamano', models.IntegerField(primary_key=True, serialize=False, verbose_name='id_tamano')),
                ('descripcion', models.CharField(max_length=30, verbose_name='Descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('idTipoIdentificacion', models.AutoField(primary_key=True, serialize=False, verbose_name='id_tipo_identificacion')),
                ('nomTipoIdentificacion', models.CharField(max_length=30, verbose_name='nom_tipo_identificacion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('idTipoProducto', models.AutoField(primary_key=True, serialize=False, verbose_name='id_tipo_producto')),
                ('nombre', models.CharField(max_length=30, unique=True, verbose_name='nombre')),
                ('descripcion', models.CharField(max_length=50, unique=True, verbose_name='descripcion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('idProveedor', models.AutoField(primary_key=True, serialize=False, verbose_name='id_proveedor')),
                ('nombreProveedor', models.CharField(max_length=100, verbose_name='nombre_proveedor')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='email')),
                ('telefono', models.CharField(max_length=10, verbose_name='telefono')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('idBario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrio', to='tiomikeApp.barrio')),
                ('idTipoIdentificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipo_identificacion', to='tiomikeApp.tipoidentificacion')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nomProducto', models.CharField(max_length=30, unique=True, verbose_name='nom_producto')),
                ('precio', models.FloatField(default=0, verbose_name='precio')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('idTipoProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_tipo_producto', to='tiomikeApp.tipoproducto')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('idMascota', models.AutoField(primary_key=True, serialize=False, verbose_name='id_mascota')),
                ('nomMascota', models.CharField(max_length=30, verbose_name='nom_mascota')),
                ('edadMascota', models.IntegerField(default=0, verbose_name='edad_mascota')),
                ('peso', models.FloatField(default=0, verbose_name='peso')),
                ('historia', models.CharField(max_length=300, verbose_name='historia')),
                ('imagen', models.CharField(max_length=255, verbose_name='imagen')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota_cliente', to='tiomikeApp.cliente')),
                ('idGenero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota_genero', to='tiomikeApp.genero')),
                ('idRaza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='masctora_raza', to='tiomikeApp.raza')),
                ('idTamano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota_tamano', to='tiomikeApp.tamano')),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idFactura', models.AutoField(primary_key=True, serialize=False, verbose_name='id_factura')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='fecha')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura_cliente', to='tiomikeApp.cliente')),
                ('idProducto', models.ManyToManyField(related_name='factura_producto', through='tiomikeApp.DetalleFactura', to='tiomikeApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMascota',
            fields=[
                ('idDetalleMascota', models.AutoField(primary_key=True, serialize=False, verbose_name='id_detalle_mascota')),
                ('fecha', models.DateTimeField(verbose_name='fecha')),
                ('historial', models.CharField(max_length=255, verbose_name='historial')),
                ('idMascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascota', to='tiomikeApp.mascota')),
            ],
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idFactura',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='factura', to='tiomikeApp.factura'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='idProducto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto', to='tiomikeApp.producto'),
        ),
        migrations.CreateModel(
            name='DetalleCita',
            fields=[
                ('idDetalleCita', models.AutoField(primary_key=True, serialize=False, verbose_name='id_detalle_cita')),
                ('recomendacion', models.TextField(verbose_name='recomendacion')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('idCita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_cita_cita', to='tiomikeApp.cita')),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_cita_producto', to='tiomikeApp.producto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idGenero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_genero', to='tiomikeApp.genero'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='idTipoIdentificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cliente_tipo_identificacion', to='tiomikeApp.tipoidentificacion'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='idDepartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamento', to='tiomikeApp.departamento'),
        ),
        migrations.AddField(
            model_name='cita',
            name='idMascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cita_mascota', to='tiomikeApp.mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='idProducto',
            field=models.ManyToManyField(related_name='cita_producto', through='tiomikeApp.DetalleCita', to='tiomikeApp.producto'),
        ),
        migrations.AddField(
            model_name='barrio',
            name='idCuidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barrio_ciudad', to='tiomikeApp.ciudad'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=100, verbose_name='password')),
                ('nombre', models.CharField(max_length=30, verbose_name='nombre')),
                ('email', models.EmailField(max_length=100, verbose_name='email')),
                ('estado', models.BooleanField(default=True, verbose_name='estado')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('idRol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='tiomikeApp.rol')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
