# Generated by Django 4.0.4 on 2022-06-01 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiomikeApp', '0002_alter_producto_idproducto_alter_rol_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rol',
            old_name='id',
            new_name='idRol',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='id',
            new_name='idUsuario',
        ),
    ]
