# Generated by Django 4.0.4 on 2022-06-01 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiomikeApp', '0004_alter_rol_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='idUsuario',
            new_name='id',
        ),
    ]
