from .usuario import Usuario
from .barrio import Barrio
from .departamento import Departamento
from .detalleFactura import DetalleFactura
from .proveedor import Proveedor
from .cita import Cita
from .estado import Estado
from .mascota import Mascota
from .tipoIdentificacion import TipoIdentificacion
from .raza import Raza
from .detalleCita import DetalleCita
from .producto import Producto
from .tipoProducto import TipoProducto
from .ciudad import Ciudad
from .cliente import Cliente
from .detalleMascota import DetalleMascota
from .factura import Factura
from .tamano import Tamano
from .genero import Genero
from .rol import Rol