from .barrioSerializer import BarrioSerializer
from .ciudadSerializer import CiudadSerializer
from .clienteSerializer import ClienteSerializer
from .generoSerializer import GeneroSerializer
from .rolSerializer import RolSerializer
from .tamanoSerializer import TamanoSerializer
from .tipoIdentificacionSerializer import TipoIdentificacionSerializer
from .usuarioSerializer import UsuarioSerializer